In [2]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("/content/breast-cancer.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,569.0,3.037183e+07,1.250206e+08,8670.000000,869218.000000,906024.000000,8.813129e+06,9.113205e+08
radius_mean,569.0,1.412729e+01,3.524049e+00,6.981000,11.700000,13.370000,1.578000e+01,2.811000e+01
texture_mean,569.0,1.928965e+01,4.301036e+00,9.710000,16.170000,18.840000,2.180000e+01,3.928000e+01
perimeter_mean,569.0,9.196903e+01,2.429898e+01,43.790000,75.170000,86.240000,1.041000e+02,1.885000e+02
area_mean,569.0,6.548891e+02,3.519141e+02,143.500000,420.300000,551.100000,7.827000e+02,2.501000e+03
smoothness_mean,569.0,9.636028e-02,1.406413e-02,0.052630,0.086370,0.095870,1.053000e-01,1.634000e-01
compactness_mean,569.0,1.043410e-01,5.281276e-02,0.019380,0.064920,0.092630,1.304000e-01,3.454000e-01
concavity_mean,569.0,8.879932e-02,7.971981e-02,0.000000,0.029560,0.061540,1.307000e-01,4.268000e-01
concave points_mean,569.0,4.891915e-02,3.880284e-02,0.000000,0.020310,0.033500,7.400000e-02,2.012000e-01
symmetry_mean,569.0,1.811619e-01,2.741428e-02,0.106000,0.161900,0.179200,1.957000e-01,3.040000e-01
fractal_dimension_mean,569.0,6.279761e-02,7.060363e-03,0.049960,0.057700,0.061540,6.612000e-02,9.744000e-02
radius_se,569.0,4.051721e-01,2.773127e-01,0.111500,0.232400,0.324200,4.789000e-01,2.873000e+00
texture_se,569.0,1.216853e+00,5.516484e-01,0.360200,0.833900,1.108000,1.474000e+00,4.885000e+00
perimeter_se,569.0,2.866059e+00,2.021855e+00,0.757000,1.606000,2.287000,3.357000e+00,2.198000e+01
area_se,569.0,4.033708e+01,4.549101e+01,6.802000,17.850000,24.530000,4.519000e+01,5.422000e+02
smoothness_se,569.0,7.040979e-03,3.002518e-03,0.001713,0.005169,0.006380,8.146000e-03,3.113000e-02
compactness_se,569.0,2.547814e-02,1.790818e-02,0.002252,0.013080,0.020450,3.245000e-02,1.354000e-01
concavity_se,569.0,3.189372e-02,3.018606e-02,0.000000,0.015090,0.025890,4.205000e-02,3.960000e-01
concave points_se,569.0,1.179614e-02,6.170285e-03,0.000000,0.007638,0.010930,1.471000e-02,5.279000e-02
symmetry_se,569.0,2.054230e-02,8.266372e-03,0.007882,0.015160,0.018730,2.348000e-02,7.895000e-02
fractal_dimension_se,569.0,3.794904e-03,2.646071e-03,0.000895,0.002248,0.003187,4.558000e-03,2.984000e-02
radius_worst,569.0,1.626919e+01,4.833242e+00,7.930000,13.010000,14.970000,1.879000e+01,3.604000e+01
texture_worst,569.0,2.567722e+01,6.146258e+00,12.020000,21.080000,25.410000,2.972000e+01,4.954000e+01
perimeter_worst,569.0,1.072612e+02,3.360254e+01,50.410000,84.110000,97.660000,1.254000e+02,2.512000e+02
area_worst,569.0,8.805831e+02,5.693570e+02,185.200000,515.300000,686.500000,1.084000e+03,4.254000e+03
smoothness_worst,569.0,1.323686e-01,2.283243e-02,0.071170,0.116600,0.131300,1.460000e-01,2.226000e-01
compactness_worst,569.0,2.542650e-01,1.573365e-01,0.027290,0.147200,0.211900,3.391000e-01,1.058000e+00
concavity_worst,569.0,2.721885e-01,2.086243e-01,0.000000,0.114500,0.226700,3.829000e-01,1.252000e+00
concave points_worst,569.0,1.146062e-01,6.573234e-02,0.000000,0.064930,0.099930,1.614000e-01,2.910000e-01
symmetry_worst,569.0,2.900756e-01,6.186747e-02,0.156500,0.250400,0.282200,3.179000e-01,6.638000e-01
fractal_dimension_worst,569.0,8.394582e-02,1.806127e-02,0.055040,0.071460,0.080040,9.208000e-02,2.075000e-01

In [6]:
df.shape

(569, 32)

In [7]:
df.drop(columns='id', inplace=True)

In [8]:
df.shape

(569, 31)

In [9]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [10]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [11]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [12]:
X_train.shape

(455, 30)

In [13]:
y_train.shape

(455,)

In [14]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
X_train

array([[-1.07775032, -1.05128461, -1.03897441, ..., -1.10458471,
        -0.75164241,  0.05310333],
       [-0.03872606, -0.71667039, -0.11684988, ..., -1.03374003,
        -0.5738378 , -1.01272496],
       [-0.15927584, -0.11898015, -0.1555317 , ...,  0.45552829,
         1.03298909,  0.154257  ],
       ...,
       [-0.62425354, -0.07513414, -0.65174034, ..., -0.6701829 ,
        -0.58536217, -0.22978408],
       [ 0.27412931,  0.11409597,  0.17971069, ..., -0.84752411,
        -0.40261854, -1.32018642],
       [-0.58120005,  1.29793803, -0.56439431, ...,  0.11125071,
        -0.47999647, -0.08233973]])

In [17]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [18]:
type(X_train)

numpy.ndarray

In [19]:
type(y_train)

numpy.ndarray

In [20]:
type(y_test)

numpy.ndarray

### numpy array to tensor

In [21]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [22]:
type(X_train_tensor)
type(y_test_tensor)

torch.Tensor

In [23]:
class MySimpleNN():
  def __init__(self, X):
    self.weight = torch.rand( X.shape[1], 1, dtype=torch.float64, requires_grad=True )
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weight) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamping

    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [24]:
torch.rand(30, 1)

tensor([[0.9292],
        [0.9690],
        [0.5144],
        [0.3166],
        [0.5012],
        [0.9372],
        [0.7047],
        [0.8671],
        [0.3547],
        [0.6815],
        [0.2678],
        [0.1936],
        [0.7710],
        [0.8698],
        [0.7514],
        [0.7177],
        [0.0356],
        [0.2235],
        [0.1511],
        [0.8148],
        [0.6432],
        [0.7252],
        [0.0251],
        [0.2390],
        [0.9279],
        [0.3622],
        [0.9729],
        [0.9083],
        [0.3595],
        [0.3362]])

In [25]:
model = MySimpleNN(X_train_tensor)

In [26]:
model.weight

tensor([[0.7615],
        [0.2513],
        [0.0182],
        [0.9637],
        [0.9326],
        [0.4829],
        [0.7246],
        [0.0702],
        [0.8661],
        [0.5470],
        [0.9178],
        [0.7826],
        [0.7461],
        [0.3697],
        [0.6617],
        [0.6010],
        [0.0795],
        [0.6570],
        [0.9999],
        [0.7947],
        [0.8490],
        [0.1853],
        [0.7923],
        [0.5182],
        [0.4303],
        [0.0702],
        [0.3061],
        [0.2337],
        [0.8228],
        [0.2682]], dtype=torch.float64, requires_grad=True)

In [27]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

### Parameters

In [28]:
learning_rate = 0.1
epochs = 25

### Pipline Create

In [29]:
model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameter update
  with torch.no_grad():
    model.weight -= learning_rate*model.weight.grad
    model.bias -= learning_rate * model.bias.grad
  # zero gradient

  model.weight.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epochs
  print(f"{epoch + 1}, Loss = {loss.item()}")

1, Loss = 3.662528426696627
2, Loss = 3.5459295619001088
3, Loss = 3.4228593240821277
4, Loss = 3.2981470791709917
5, Loss = 3.1730157873629783
6, Loss = 3.044835417920888
7, Loss = 2.91657060095965
8, Loss = 2.7875621535760358
9, Loss = 2.6529913760915873
10, Loss = 2.517328669615373
11, Loss = 2.3804864955445626
12, Loss = 2.247039404818695
13, Loss = 2.1153214346081826
14, Loss = 1.9872293005721724
15, Loss = 1.8612041359645226
16, Loss = 1.7374352258390322
17, Loss = 1.61776429422012
18, Loss = 1.5077406464091876
19, Loss = 1.4068891266926145
20, Loss = 1.313160525061594
21, Loss = 1.2325576567836785
22, Loss = 1.1645731661405687
23, Loss = 1.1080643022320056
24, Loss = 1.061410452220857
25, Loss = 1.022797606750579

### Model Evaluation

In [45]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy =  {accuracy.item()}")

 Accuracy =  0.5680209398269653

In [34]:
y_pred

tensor([[0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.]])

In [41]:
accuracy

tensor(0.5680)

 Accuracy =  0.5680209398269653